### ISSUE TITLE
EIG Promotion 6: filtre "expertises" cassé pour les valeurs Data Engineering et Data Science

### ISSUE THREAD

**Issue by vvvvalvalval** [entrepreneur-interet-general/site-eig-v2#1571]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Sur [la page des défis](https://eig.etalab.gouv.fr/defis/), le filtre "expertise=Data Engineering" n'affiche aucun résultat sur la Promotion 6, bien que certains défis demandent cette compétence dans leur contenu. Même chose pour "expertise=Data Science".

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. https://eig.etalab.gouv.fr/defis/
2. Filtrer sur la Promotion 6.
3. Filtrer sur l'expertise "Data Engineering"
4. Constater que la liste des défis est vide, ce qui est une erreur, puisque par exemple [le défi Champollion](https://eig.etalab.gouv.fr/defis/champollion/) demande un(e) _"Ingénieur(e) de la donnée (ou « data engineer »)"_

**- What is the expected behavior?**
On devrait voir une liste non-vide de défis de la Promotion 6 demandant ces expertises.

**- Please mention your node.js, NPM, Hugo and operating system version.**
N/A

## Analyse et pistes de résolution

Je constate que Champollion a [dans ses métadonnées](https://raw.githubusercontent.com/entrepreneur-interet-general/site-eig-v2/a824945b7d1ae2dc1f5bc789fc011149d9488ebd/site/content/defis/champollion.md) l'expertise `Ingénierie de la donnée`, contrairement par exemple à [BatID](https://raw.githubusercontent.com/entrepreneur-interet-general/site-eig-v2/a824945b7d1ae2dc1f5bc789fc011149d9488ebd/site/content/defis/batid.md) de la promotion 5 qui écrit `Data engineering`. Mon soupçon est que **cette différence de formulation conduit à un échec de correspondance automatique** avec les [métadonnées](https://raw.githubusercontent.com/entrepreneur-interet-general/site-eig-v2/a824945b7d1ae2dc1f5bc789fc011149d9488ebd/site/content/expertises/data-engineering.md) `title: Data Engineering` de l'expertise en question, la jointure passant probablement par [partials/defis.html](https://github.com/entrepreneur-interet-general/site-eig-v2/blob/a824945b7d1ae2dc1f5bc789fc011149d9488ebd/site/layouts/partials/defis.html#L4).

Le fonctionnement du site m'est encore assez obscur et je ne connais pas le templating Hugo, mais la résolution la plus abordable qui me viens serait de n'avoir qu'une seule formulation pour chaque expertise, qui soit la même dans toutes les métadonnées de défis et d'expertises.

## Déclaration de conflits d'intérêt

Je suis un des candidats de la promotion 6.

**Comment by elisabethfainstein** [comment]
Merci, cela a été résolu :)
